### ISSUE TITLE
Only some events are detected

### ISSUE THREAD

**Issue by yulrizka** [AlJohri/outlook-apple-calendar-sync#1]
First of all thanks for creating this script. 

I was testing it and look set it to look from 100 days ago and it seems that it only got some events.

I also try to modify the script and remove all other filters (eg: recurrence, blacklist, etc) except for the date. And got the same result. Do you maybe have any idea why and how I can debug it?

**Comment by AlJohri** [comment]
thanks @yulrizka! I wanted to say that I stopped using this after finding out that outlook and apple calendar native sync seems to now be available. I think I just had to log in using "Internet Accounts" in System Preferences. Let me know if that works for you!

to debug, i think you can run the script locally using `./outlook-apple-calendar-sync` or `/usr/bin/osascript -l JavaScript outlook-apple-calendar-sync` instead of through homebrew

then hopefully you'll see the `log` statements get printed out like

https://github.com/AlJohri/outlook-apple-calendar-sync/blob/36b993c9b959a2b23a58031480c97b973cb01efa/sync.jxa#L123

perhaps you can print out the `events` variable from:

https://github.com/AlJohri/outlook-apple-calendar-sync/blob/36b993c9b959a2b23a58031480c97b973cb01efa/sync.jxa#L68-L70

here were some reference scripts I found helpful as I was debugging/developing this:
- https://gist.github.com/bencharb/7baa8dd669fa146f4bd230d527477206
- https://timingapp.com/help/javascript_outlook

**Comment by yulrizka** [comment]
Unfortunately the the apple calendar doesn't work for me due to some restriction.  But i found what causes it. Apparently the apple script integration breaks when i switch to the "new outlook". reverting it back make the old outlook sync again and then i can view the events
